# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_productclass_name_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
