# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170328_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_richtext_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Richtext'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_richtext_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Richtext'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
