# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('catalogue', '0014_auto_20170328_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name=b'\xd0\xa1\xd0\xb0\xd0\xb9\xd1\x82'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name=b'\xd0\xa1\xd0\xb0\xd0\xb9\xd1\x82'),
        ),
    ]
