# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20170427_1529'),
        ('catalogue', '0017_auto_20170426_1728'),
    ]

    operations = [
    ]
