# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_merge_20170428_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'categories', verbose_name='Image'),
        ),
    ]
