# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_productclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'product_classes', verbose_name='Image'),
        ),
    ]
