# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_attributeoptiongroup_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x91\xd0\xb5\xd1\x81\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift',
            field=models.BooleanField(default=False, verbose_name=b'+\xd0\x9f\xd0\xbe\xd0\xb4\xd0\xb0\xd1\x80\xd0\xbe\xd0\xba'),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xb8\xd0\xbd\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\xa0\xd0\xb5\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xb4\xd1\x83\xd0\xb5\xd0\xbc'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x90\xd0\xba\xd1\x86\xd0\xb8\xd1\x8f'),
        ),
        migrations.AddField(
            model_name='product',
            name='super_price',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80\xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_sale',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\xa5\xd0\xb8\xd1\x82 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb4\xd0\xb0\xd0\xb6'),
        ),
    ]
