# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20170508_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoptiongroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='image',
            field=models.ImageField(upload_to='products/images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='catalogue.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='\u0411\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gift',
            field=models.BooleanField(default=False, verbose_name='+\u041f\u043e\u0434\u0430\u0440\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='\u041d\u043e\u0432\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0443\u0435\u043c'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='super_price',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0443\u043f\u0435\u0440\u0446\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_sale',
            field=models.BooleanField(default=False, verbose_name='\u0425\u0438\u0442 \u043f\u0440\u043e\u0434\u0430\u0436'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalogue.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(help_text='\u0412\u0441\u0442\u0430\u0432\u044c\u0442\u0435 url', verbose_name='\u0412\u0438\u0434\u0435\u043e'),
        ),
    ]
