# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20170607_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
