# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20170511_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='productattributevalue',
            old_name='value_richtext_ua',
            new_name='value_richtext_uk',
        ),
        migrations.RenameField(
            model_name='productattributevalue',
            old_name='value_text_ua',
            new_name='value_text_uk',
        ),
        migrations.RenameField(
            model_name='productclass',
            old_name='name_ua',
            new_name='name_uk',
        ),
    ]
