# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_category_description_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
