# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20170619_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0430\u0442\u044c\u0438 (\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0430\u0442\u044c\u0438 (\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0430\u0442\u044c\u0438 (\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f)'),
        ),
    ]
