# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_filterdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterdescription',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u0442\u0440\u043e\u0432', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438 \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u0442\u0440\u043e\u0432'},
        ),
        migrations.AlterField(
            model_name='filterdescription',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='filterdescription',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
