# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20170622_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_uk',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ru',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, verbose_name='Slug', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_uk',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, verbose_name='Slug', null=True),
        ),
    ]
