# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 11:41
from __future__ import unicode_literals

# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 10:54
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):

    models_to_update = [
        apps.get_model('catalogue', 'Product'),
        apps.get_model('catalogue', 'Category')
    ]

    for model in models_to_update:
        for obj in model.objects.all():
            obj.slug_ru = obj.__dict__['slug']
            obj.slug_uk = obj.__dict__['slug']
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_translations_for_slugs'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
