# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20170629_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_in_side_menu',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432 \u0431\u043e\u043a\u043e\u0432\u043e\u043c \u043c\u0435\u043d\u044e'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_in_side_menu_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432 \u0431\u043e\u043a\u043e\u0432\u043e\u043c \u043c\u0435\u043d\u044e'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_in_side_menu_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432 \u0431\u043e\u043a\u043e\u0432\u043e\u043c \u043c\u0435\u043d\u044e'),
        ),
    ]
