# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_side_menu_config_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False, verbose_name='\u041d\u043e\u0432\u0438\u043d\u043a\u0430'),
        ),
    ]
