# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20170821_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoptiongroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
    ]
