# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20170822_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(blank=True, help_text='Choose what type of product this is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.ProductClass', verbose_name='Product type'),
        ),
    ]
