# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_auto_20170908_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='option_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='option_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Option'),
        ),
    ]
