# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_auto_20171009_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='\u041a\u0442\u043e-\u0442\u043e \u043e\u0441\u0442\u0430\u0432\u0438\u043b \u043a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043d\u0430 \u0432\u0430\u0448 \u043e\u0442\u0437\u044b\u0432. \u0427\u0442\u043e \u0431\u044b \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c \u044d\u0442\u043e\u0442 \u043a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \n \u043f\u0435\u0440\u0435\u0439\u0434\u0438\u0442\u0435, \u043f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e \u0441\u0441\u044b\u043b\u043a\u0435 http://{0}/{1}', max_length=250, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('email_subject', models.CharField(default='\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435 \u043e\u0431 \u043e\u0442\u0432\u0435\u0442\u0435 \u043d\u0430 \u0432\u0430\u0448 \u043e\u0442\u0437\u044b\u0432', max_length=250, verbose_name='\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435')),
                ('subject_order', models.CharField(default='Order notification', max_length=250, verbose_name='\u041e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0435 \u0437\u0430\u043a\u0430\u0437\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u0435\u043c\u0435\u0438\u043b',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442 \u0435\u043c\u0435\u0438\u043b',
            },
        ),
    ]
