# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_emailonorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailonorder',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u0435\u043c\u0435\u0438\u043b'},
        ),
    ]
