# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430 \u0434\u043e\u043b\u0436\u0435\u043d \u0431\u044b\u0442\u044c \u0432\u0432\u0435\u0434\u0435\u043d \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435: '+999999999'. \u0414\u043e\u043f\u0443\u0441\u043a\u0430\u0435\u0442\u0441\u044f \u0434\u043e 15 \u0446\u0438\u0444\u0440 \u0432 \u043d\u043e\u043c\u0435\u0440\u0435", regex='^\\+?1?\\d{9,15}$')])),
                ('operator', models.CharField(choices=[('kievstar', 'Kievstar'), ('life', 'Life'), ('vodafone', 'Vodafone')], default='kievstar', max_length=20, verbose_name='\u041e\u043f\u0435\u0440\u0430\u0442\u043e\u0440')),
                ('sign', models.CharField(choices=[('w', '\u0411\u0435\u0441\u0446\u0432\u0435\u0442\u043d\u044b\u0439 \u0437\u043d\u0430\u0447\u043e\u043a'), ('c', '\u0426\u0432\u0435\u0442\u043d\u043e\u0439 \u0437\u043d\u0430\u0447\u043e\u043a')], default='c', max_length=1)),
            ],
        ),
    ]
