# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contacts', '0003_auto_20170404_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('facebook', 'facebook'), ('vkontakte', '\u0412\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'), ('twitter', 'Twitter'), ('odnoklassniki', '\u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u0441\u043d\u0438\u043a\u0438'), ('pinterest', 'Pinterest'), ('google', 'Google+'), ('youtube', 'YouTube')], default='facebook', max_length=20, verbose_name='\u041e\u043f\u0435\u0440\u0430\u0442\u043e\u0440')),
                ('reference', models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialnetrefs', to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0443\u044e \u0441\u0435\u0442\u044c',
                'verbose_name_plural': '\u0421\u0441\u044b\u043b\u043a\u0438 \u043d\u0430 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0435\u0442\u0438',
            },
        ),
    ]
