# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_timetable_workschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': '\u0413\u0440\u0430\u0444\u0438\u043a', 'verbose_name_plural': '\u0413\u0440\u0430\u0444\u0438\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workschedules', to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='timetable',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='timetable',
            field=models.ManyToManyField(related_name='workschedules', to='contacts.Timetable', verbose_name='\u0413\u0440\u0430\u0444\u0438\u043a'),
        ),
    ]
