# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20170424_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': '\u0413\u0440\u0430\u0444\u0438\u043a \u0440\u0430\u0431\u043e\u0442\u044b', 'verbose_name_plural': '\u0413\u0440\u0430\u0444\u0438\u043a\u0438 \u0440\u0430\u0431\u043e\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='timetable',
            field=models.ManyToManyField(related_name='workschedules', to='contacts.Timetable', verbose_name='\u0413\u0440\u0430\u0444\u0438\u043a\u0438'),
        ),
    ]
