# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contacts', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
    ]
