# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flatpages', '0001_initial'),
        ('contacts', '0010_auto_20170523_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('flatpages.flatpage',),
        ),
    ]
