# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_flatpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatPage',
        ),
    ]
