# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contacts', '0013_flatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='site',
            field=models.ManyToManyField(blank=True, null=True, related_name='flatpages', to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
    ]
