# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20170524_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flatpage',
            table='contacts_flatpages',
        ),
    ]
