# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20170524_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435-\u043c\u0435\u0442\u043a\u0430 \u0434\u043b\u044f URL')),
                ('address', models.CharField(default='\u0443\u043b. \u0421\u043c\u0435\u043b\u044f\u043d\u0441\u043a\u0430\u044f 159/3', max_length=70, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=200, verbose_name='\u041a\u043b\u044e\u0447 API \u043a\u0430\u0440\u0442 Google')),
            ],
            options={
                'verbose_name': '\u0413\u043e\u0440\u043e\u0434',
                'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430',
            },
        ),
    ]
