# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contacts', '0018_auto_20170607_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
    ]
