# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20170608_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='operator',
            field=models.CharField(choices=[('kievstar', 'Kievstar'), ('life', 'Life'), ('vodafone', 'Vodafone'), ('cityphone', '\u0413\u043e\u0440\u043e\u0434\u0441\u043a\u043e\u0439 \u043d\u043e\u043c\u0435\u0440')], default='kievstar', max_length=20, verbose_name='\u041e\u043f\u0435\u0440\u0430\u0442\u043e\u0440'),
        ),
    ]
