# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_auto_20170617_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpage',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='flatpage',
            name='slug_uk',
        ),
    ]
