# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_remove_flatpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='address_ru',
            field=models.CharField(default='\u0443\u043b. \u0421\u043c\u0435\u043b\u044f\u043d\u0441\u043a\u0430\u044f 159/3', max_length=70, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='city',
            name='address_uk',
            field=models.CharField(default='\u0443\u043b. \u0421\u043c\u0435\u043b\u044f\u043d\u0441\u043a\u0430\u044f 159/3', max_length=70, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='weekdays_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0414\u043d\u0438 \u043d\u0435\u0434\u0435\u043b\u0438'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='weekdays_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0414\u043d\u0438 \u043d\u0435\u0434\u0435\u043b\u0438'),
        ),
    ]
