# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_auto_20170619_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='daytime_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0434\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='daytime_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0434\u043d\u044f'),
        ),
    ]
