# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_auto_20170619_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='slug_ru',
            field=models.SlugField(default='', null=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='slug_uk',
            field=models.SlugField(default='', null=True),
        ),
    ]
