# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 10:54
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist


def forwards_func(apps, schema_editor):
    flatpage_model = apps.get_model('contacts', 'FlatPage')
    flatpage_translation_model = apps.get_model('contacts', 'FlatPageTranslation')

    for obj in flatpage_model.objects.all():
        obj.slug_ru = _get_translation(obj, flatpage_translation_model, 'ru')
        obj.slug_uk = _get_translation(obj, flatpage_translation_model, 'uk')
        obj.save()   # Note this only calls Model.save()


def backwards_func(apps, schema_editor):
    flatpage_model = apps.get_model('contacts', 'FlatPage')
    flatpage_translation_model = apps.get_model('contacts', 'FlatPageTranslation')

    for obj in flatpage_model.objects.all():
        if obj.slug_ru:
            flatpage_translation_model.objects.create(
                master_id=obj.pk,
                language_code='ru',
                slug=obj.slug_ru
            )
        if obj.slug_uk:
            flatpage_translation_model.objects.create(
                master_id=obj.pk,
                language_code='uk',
                slug=obj.slug_uk
            )


def _get_translation(obj, flatpage_translation_model, language_code):
    translations = flatpage_translation_model.objects.filter(master_id=obj.pk)
    try:
        # Try default translation
        return translations.get(language_code=language_code).slug
    except ObjectDoesNotExist:
        return None


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_added_slug_field_flatpage'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
