# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_auto_20170802_0611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flatpagetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='flatpagetranslation',
            name='master',
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='slug_ru',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='slug_uk',
            field=models.SlugField(null=True),
        ),
        migrations.DeleteModel(
            name='FlatPageTranslation',
        ),
    ]
