# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_stockrecord_previous_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='price_updated',
            field=models.BooleanField(default=True),
        ),
    ]
