# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_stockrecord_price_updated_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='partner.Partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='partner_sku',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Partner SKU'),
        ),
    ]
