# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.PositiveSmallIntegerField(blank=True, choices=[(0, '/path/to/template')], default=0, null=True, verbose_name='\u0448\u0430\u0431\u043b\u043e\u043d')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0441\u0430\u0439\u0442')),
            ],
        ),
    ]
