# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='sites.Site', verbose_name='\u0441\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='template',
            field=models.CharField(blank=True, choices=[('defro', 'Defro')], default='defro', max_length=20, null=True, verbose_name='\u0448\u0430\u0431\u043b\u043e\u043d'),
        ),
    ]
