# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20170426_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email \u0430\u0434\u0440\u0435\u0441'),
        ),
    ]
