# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=128, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
