# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('config', '0009_auto_20170509_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('site', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 4',
            },
        ),
        migrations.CreateModel(
            name='TextOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('site', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 1',
            },
        ),
        migrations.CreateModel(
            name='TextThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('site', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 3',
            },
        ),
        migrations.CreateModel(
            name='TextTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('site', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 2',
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='undercat_block_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043f\u043e\u0434 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u043e\u043c'),
        ),
    ]
