# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20170514_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textfour',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 1'},
        ),
        migrations.AlterModelOptions(
            name='textthree',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 1'},
        ),
        migrations.AlterModelOptions(
            name='texttwo',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 1'},
        ),
    ]
