# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_auto_20170514_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textfour',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 4'},
        ),
        migrations.AlterModelOptions(
            name='textthree',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 3'},
        ),
        migrations.AlterModelOptions(
            name='texttwo',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 2'},
        ),
        migrations.AlterField(
            model_name='textfour',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='textone',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='textthree',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='texttwo',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
