# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20170519_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textfour',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 4', 'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442\u044b 4'},
        ),
        migrations.AlterModelOptions(
            name='textone',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 1', 'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442\u044b 1'},
        ),
        migrations.AlterModelOptions(
            name='textthree',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 3', 'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442\u044b 3'},
        ),
        migrations.AlterModelOptions(
            name='texttwo',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442 2', 'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442\u044b 2'},
        ),
    ]
