# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20170525_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f'),
        ),
    ]
