# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20170607_1750'),
        ('config', '0017_metatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='brand_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_config', to='catalogue.ProductAttribute', verbose_name='\u041f\u043e\u043b\u0435 \u0431\u0440\u0435\u043d\u0434\u0430 \u043a\u043e\u0442\u043b\u0430'),
        ),
    ]
