# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_configuration_brand_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='type',
            field=models.CharField(choices=[('MP', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'), ('SC', '\u0420\u0430\u0437\u0434\u0435\u043b'), ('SS', '\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b'), ('CA', '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'), ('BR', '\u0411\u0440\u0435\u043d\u0434'), ('BF', '\u0411\u0440\u0435\u043d\u0434 + \u0444\u0438\u043b\u044c\u0442\u0440'), ('PD', '\u0422\u043e\u0432\u0430\u0440'), ('FP', '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430')], max_length=2, unique=True, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
