# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_auto_20170615_1734'),
        ('config', '0017_siteconfig_copyright'),
    ]

    operations = [
    ]
