# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_merge_20170615_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='description_meta_ru',
            field=models.TextField(default='[title]', null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='description_meta_uk',
            field=models.TextField(default='[title]', null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='h1_ru',
            field=models.CharField(default='[title]', max_length=250, null=True, verbose_name='H1 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='h1_uk',
            field=models.CharField(default='[title]', max_length=250, null=True, verbose_name='H1 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='title_meta_ru',
            field=models.CharField(default='[title]', max_length=250, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='title_meta_uk',
            field=models.CharField(default='[title]', max_length=250, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='title_ru',
            field=models.CharField(default='[title]', max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='title_uk',
            field=models.CharField(default='[title]', max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
