# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('config', '0022_auto_20170626_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('title_meta', models.CharField(max_length=250, verbose_name='Meta title')),
                ('description_meta', models.TextField(verbose_name='Meta description')),
                ('h1', models.CharField(max_length=250, verbose_name='H1 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0442\u0430 \u0442\u0435\u0433\u044b \u0434\u043b\u044f \u043e\u0431\u044c\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u041c\u0435\u0442\u0430 \u0442\u0435\u0433\u044b \u0434\u043b\u044f \u043e\u0431\u044c\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.AlterUniqueTogether(
            name='modelmetatag',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
