# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20170629_0819'),
        ('config', '0023_auto_20170628_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='brand_attribute',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='power_attribute',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='brand_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_config', to='catalogue.ProductAttribute', verbose_name='\u0410\u0442\u0440\u0438\u0431\u0443\u0442 \u0431\u0440\u0435\u043d\u0434\u0430 \u043a\u043e\u0442\u043b\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='power_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.ProductAttribute', verbose_name='\u0410\u0442\u0440\u0438\u0431\u0443\u0442 \u043c\u043e\u0449\u043d\u043e\u0441\u0442\u0438 \u043a\u043e\u0442\u043b\u0430'),
        ),
    ]
