# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_auto_20170703_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('text', models.CharField(max_length=128, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='FuelConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('wood', '\u0414\u0440\u043e\u0432\u0430'), ('pellets', '\u041f\u0435\u043b\u043b\u0435\u0442\u044b'), ('coal', '\u041a\u0430\u043c\u0435\u043d\u043d\u044b\u0439 \u0443\u0433\u043e\u043b\u044c'), ('brown_coal', '\u0411\u0443\u0440\u044b\u0439 \u0443\u0433\u043e\u043b\u044c'), ('gas', '\u0413\u0430\u0437'), ('electricity', '\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u044d\u043d\u0435\u0440\u0433\u0438\u044f'), ('diesel', '\u0414\u0438\u0437\u0435\u043b\u044c\u043d\u043e\u0435 \u0442\u043e\u043f\u043b\u0438\u0432\u043e')], default='wood', max_length=20, verbose_name='\u0412\u0438\u0434 \u0442\u043e\u043f\u043b\u0438\u0432\u0430')),
                ('fuel_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u044b\u0439 \u043e\u0431\u044a\u0435\u043c')),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0426\u0435\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0431\u044a\u0435\u043c \u0438 \u0446\u0435\u043d\u0430 \u0442\u043e\u043f\u043b\u0438\u0432\u0430',
                'verbose_name_plural': '\u041e\u0431\u044a\u0435\u043c\u044b \u0438 \u0446\u0435\u043d\u044b \u0442\u043e\u043f\u043b\u0438\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='OverviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043e\u0431\u0437\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u041e\u0431\u0437\u043e\u0440',
                'verbose_name_plural': '\u041e\u0431\u0437\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f \u043e\u0441\u0442\u0430\u0432\u0438\u0432\u0448\u0435\u0433\u043e \u043e\u0442\u0437\u044b\u0432')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u0442\u0437\u044b\u0432\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'},
        ),
        migrations.AddField(
            model_name='configuration',
            name='credit_block_text',
            field=models.CharField(blank=True, max_length=210, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 '\u041a\u0440\u0435\u0434\u0438\u0442'"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_advanced',
            field=models.BooleanField(default=False, verbose_name="\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a '\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0443\u0441\u043b\u0443\u0433\u0438'?"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_benefits',
            field=models.BooleanField(default=False, verbose_name="\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a '\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432'?"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_calculator',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u043a\u0430\u043b\u044c\u043a\u0443\u043b\u044f\u0442\u043e\u0440 \u043a\u043e\u0442\u043b\u043e\u0432?'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_credit',
            field=models.BooleanField(default=False, verbose_name="\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a '\u041a\u0440\u0435\u0434\u0438\u0442'?"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_reviews',
            field=models.BooleanField(default=False, verbose_name="\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a '\u041e\u0431\u0437\u043e\u0440\u044b \u0438 \u043e\u0442\u0437\u044b\u0432\u044b'?"),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='config.Configuration', verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='overviewitem',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='config.Configuration', verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='fuelconfiguration',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='config.Configuration', verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='config.Configuration', verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
