# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_auto_20170806_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefititem',
            name='text',
            field=models.CharField(max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
