# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_auto_20170806_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelconfiguration',
            name='fuel_volume',
        ),
    ]
