# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_auto_20170806_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0418\u043c\u044f \u043e\u0441\u0442\u0430\u0432\u0438\u0432\u0448\u0435\u0433\u043e \u043e\u0442\u0437\u044b\u0432'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0418\u043c\u044f \u043e\u0441\u0442\u0430\u0432\u0438\u0432\u0448\u0435\u0433\u043e \u043e\u0442\u0437\u044b\u0432'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u0442\u0437\u044b\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u0442\u0437\u044b\u0432\u0430'),
        ),
    ]
