# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('config', '0032_auto_20170806_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landing_config', to='sites.Site', verbose_name='\u0441\u0430\u0439\u0442'),
            preserve_default=False,
        ),
    ]
