# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 10:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_configuration_footer_map_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAndPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_block', models.CharField(choices=[('delivery', "\u0414\u043b\u044f \u0431\u043b\u043e\u043a\u0430 '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430'"), ('pay', "\u0414\u043b\u044f \u0431\u043b\u043e\u043a\u0430 '\u041e\u043f\u043b\u0430\u0442\u0430'")], default='delivery', max_length=30, verbose_name='\u0414\u043b\u044f \u0431\u043b\u043e\u043a\u0430')),
                ('icon', models.ImageField(upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('title', models.CharField(max_length=30, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': "\u0411\u043b\u043e\u043a '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430/\u041e\u043f\u043b\u0430\u0442\u0430'",
                'verbose_name_plural': "\u0411\u043b\u043e\u043a\u0438 '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430/\u041e\u043f\u043b\u0430\u0442\u0430'",
            },
        ),
        migrations.AlterField(
            model_name='configuration',
            name='credit_block_text',
            field=models.TextField(blank=True, max_length=220, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 '\u041a\u0440\u0435\u0434\u0438\u0442'"),
        ),
        migrations.AddField(
            model_name='deliveryandpay',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_block', to='config.Configuration', verbose_name='\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
