# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_auto_20170807_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryandpay',
            name='icon',
            field=models.ImageField(blank=True, upload_to='deliverypay_images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='review_images', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
