# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_auto_20170807_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='show_delivery',
            field=models.BooleanField(default=True, verbose_name="\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430/\u041e\u043f\u043b\u0430\u0442\u0430'"),
        ),
    ]
