# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_configuration_show_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('side', '\u0411\u043e\u043a\u043e\u0432\u043e\u0435 \u043c\u0435\u043d\u044e')], default='header', max_length=128, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
