# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_side_menu_config_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='additional_phrase',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='additional_phrase_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='additional_phrase_uk',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='credit_block_text_ru',
            field=models.TextField(blank=True, max_length=220, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 '\u041a\u0440\u0435\u0434\u0438\u0442'"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='credit_block_text_uk',
            field=models.TextField(blank=True, max_length=220, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 '\u041a\u0440\u0435\u0434\u0438\u0442'"),
        ),
        migrations.AddField(
            model_name='configuration',
            name='general_phrase',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='general_phrase_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='general_phrase_uk',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0444\u0440\u0430\u0437\u0430'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
