# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0041_auto_20170812_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='code_webmaster_google',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041a\u043e\u0434 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f \u0434\u043b\u044f Google'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='code_webmaster_yandex',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041a\u043e\u0434 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f \u0434\u043b\u044f \u042f\u043d\u0434\u0435\u043a\u0441.\u0412\u0435\u0431\u043c\u0430\u0441\u0442\u0435\u0440'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
