# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0043_auto_20170817_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='google_tag_manager_noscript',
            field=models.TextField(blank=True, verbose_name='Iframe \u0434\u043b\u044f Google Tag Manager'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_tag_manager_script',
            field=models.TextField(blank=True, verbose_name='\u0421\u043a\u0440\u0438\u043f\u0442 Google Tag Manager'),
        ),
    ]
