# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0044_auto_20170817_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email_host',
            field=models.CharField(default='', help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 smtp.gmail.com', max_length=128, verbose_name='Email host (smtp-\u0441\u0435\u0440\u0432\u0435\u0440)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_password',
            field=models.CharField(default='', max_length=128, verbose_name='Email host password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='Email port'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c TLS?'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_username',
            field=models.CharField(default='', max_length=128, verbose_name='Email host user'),
            preserve_default=False,
        ),
    ]
