# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0045_auto_20170917_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
