# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0048_auto_20171019_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='delivery_text',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
