# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_productreview_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='advantage',
            field=models.TextField(blank=True, verbose_name='Advantage'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='disadvantage',
            field=models.TextField(blank=True, verbose_name='Disadvantage'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(blank=True, max_length=255, validators=[oscar.core.validators.non_whitespace], verbose_name='Title'),
        ),
    ]
