# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20170406_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='get_notification',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd1\x83\xd1\x87\xd0\xb0\xd1\x82\xd1\x8c \xd1\x83\xd0\xb2\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbc\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xbe\xd0\xb1 \xd0\xbe\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82\xd0\xb0\xd1\x85'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='advantage',
            field=models.TextField(blank=True, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xb5\xd0\xb8\xd0\xbc\xd1\x83\xd1\x89\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='disadvantage',
            field=models.TextField(blank=True, verbose_name=b'\xd0\x9d\xd0\xb5\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd0\xba\xd0\xb8'),
        ),
    ]
