# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20170411_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.ProductReview'),
        ),
    ]
