# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_category_site'),
        ('reviews', '0007_productreview_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'\xd0\x98\xd0\xbc\xd1\x8f')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd1\x87\xd1\x82\xd0\xb0')),
                ('phone', models.CharField(max_length=10, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd')),
                ('text', models.TextField(verbose_name=b'\xd0\x92\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name=b'\xd0\xa2\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441 \u043e \u0442\u043e\u0432\u0430\u0440\u0435',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u043e \u0442\u043e\u0432\u0430\u0440\u0435',
            },
        ),
    ]
