# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_productquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestion',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xb8 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f \xd1\x81\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'),
            preserve_default=False,
        ),
    ]
