# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_reviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanswer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 27, 15, 16, 43, 940765, tzinfo=utc), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd1\x81\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewanswer',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_answer', to='reviews.ReviewAnswer'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.ProductReview'),
        ),
    ]
