# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20170527_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewanswer',
            options={'verbose_name': '\u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u043e\u0442\u0437\u044b\u0432', 'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b \u043d\u0430 \u043e\u0442\u0437\u044b\u0432\u044b'},
        ),
        migrations.AddField(
            model_name='reviewanswer',
            name='delta_votes',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Delta Votes'),
        ),
        migrations.AddField(
            model_name='reviewanswer',
            name='total_votes',
            field=models.IntegerField(default=0, verbose_name='Total Votes'),
        ),
    ]
