# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0013_reviewanswer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')], verbose_name='Delta')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.ReviewAnswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'Vote answer',
                'verbose_name_plural': 'Votes answer',
            },
        ),
        migrations.AlterUniqueTogether(
            name='voteanswer',
            unique_together=set([('user', 'answer')]),
        ),
    ]
