# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20170529_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u041f\u043e\u0447\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='text',
            field=models.TextField(verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='advantage',
            field=models.TextField(blank=True, verbose_name='\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='disadvantage',
            field=models.TextField(blank=True, verbose_name='\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='get_notification',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u044c \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f \u043e\u0431 \u043e\u0442\u0432\u0435\u0442\u0430\u0445'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='body',
            field=models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='get_notification',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u044c \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f \u043e\u0431 \u043e\u0442\u0432\u0435\u0442\u0430\u0445'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='\u0421\u0430\u0439\u0442'),
        ),
    ]
