# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_category_site'),
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneClickOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u0441\u043e\u0437\u0434\u0430\u043d')),
                ('phone', models.CharField(max_length=12, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Product', verbose_name=b'\xd0\xa2\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80')),
            ],
        ),
    ]
