# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_slugfield_noop'),
        ('order', '0006_oneclickorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0413\u043e\u0440\u043e\u0434 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
                'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='SimpleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('order_status', models.IntegerField(choices=[(1, '\u041e\u0442\u043c\u0435\u043d\u0435\u043d'), (2, '\u0412 \u0441\u0442\u0430\u0434\u0438\u0438 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438'), (3, '\u041d\u0430 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0435'), (4, '\u041e\u0433\u0440\u0443\u0436\u0435\u043d'), (5, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], default=2, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('phone', models.CharField(max_length=12, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('address', models.CharField(max_length=100, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Basket', verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ShippingCity', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
            ],
        ),
        migrations.AlterModelOptions(
            name='oneclickorder',
            options={'verbose_name': '\u0417\u0430\u043a\u0430\u0437', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b'},
        ),
    ]
