# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170503_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
                'verbose_name_plural': '\u0421\u043f\u043e\u0441\u043e\u0431\u044b \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
            },
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='city',
            field=models.CharField(max_length=60, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.DeleteModel(
            name='ShippingCity',
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ShippingMethod', verbose_name=b'\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x81\xd0\xbe\xd0\xb1 \xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
    ]
