# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_simpleorder_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleorder',
            name='address',
        ),
    ]
