# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_simpleorder_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleorder',
            options={'verbose_name': '\u0417\u0430\u043a\u0430\u0437', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b'},
        ),
    ]
