# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_slugfield_noop'),
        ('order', '0012_auto_20170504_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneclickorder',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Basket', verbose_name=b'\xd0\x9a\xd0\xbe\xd1\x80\xd0\xb7\xd0\xb8\xd0\xbd\xd0\xb0'),
        ),
    ]
