# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_oneclickorder_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneclickorder',
            options={'verbose_name': '\u0417\u0430\u043a\u0430\u0437 \u0432 \u043e\u0434\u0438\u043d \u043a\u043b\u0438\u043a', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b \u0432 \u043e\u0434\u0438\u043d \u043a\u043b\u0438\u043a'},
        ),
    ]
