# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
