# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_callrequest_when_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430 \u043d\u0430 \u0437\u0432\u043e\u043d\u043e\u043a', 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0437\u0432\u043e\u043d\u043a\u0438'},
        ),
    ]
