# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20170517_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
