# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20170517_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default=b'UAH', max_length=12, null=True, verbose_name=b'Currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Shipping charge (excl. tax)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_incl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Shipping charge (inc. tax)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Order total (excl. tax)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_incl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Order total (inc. tax)'),
        ),
    ]
