# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20170810_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
