# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20171017_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
